# This file was generated by GoReleaser. DO NOT EDIT.
cask "compozy" do
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/compozy/compozy/releases/download/v#{version}/compozy_#{version}_darwin_x86_64.tar.gz"
      sha256 "b6eec971180824ff6f514d6b3e9907084a6c554afccd67341b9853aa1e60403f"
      rename "compozy_0.1.0_darwin_x86_64/compozy", "compozy"
    end
    on_arm do
      url "https://github.com/compozy/compozy/releases/download/v#{version}/compozy_#{version}_darwin_arm64.tar.gz"
      sha256 "41bafc4f039d1fe562d8b9e4a4ec2549a2e22de963f2454dae1101de8a9afcbb"
      rename "compozy_0.1.0_darwin_arm64/compozy", "compozy"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/compozy/compozy/releases/download/v#{version}/compozy_#{version}_linux_x86_64.tar.gz"
      sha256 "c2fe7044b5664dd3090c983f2bd9088b182d516624330c8bdd92890ede64d871"
      rename "compozy_0.1.0_linux_x86_64/compozy", "compozy"
    end
    on_arm do
      url "https://github.com/compozy/compozy/releases/download/v#{version}/compozy_#{version}_linux_arm64.tar.gz"
      sha256 "eb9b82ddbf8bd5b1ed12464787d7b307847224e2a748ff923000a75821af8fe9"
      rename "compozy_0.1.0_linux_arm64/compozy", "compozy"
    end
  end

  name "compozy"
  desc "Compozy CLI"
  homepage "https://github.com/compozy/compozy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "compozy"

  # No zap stanza required

  caveats <<~EOS
    To get started with Compozy, see https://github.com/compozy/compozy
  EOS
end
