# This file was generated by GoReleaser. DO NOT EDIT.
cask "compozy" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "25e9e43dc1c96ec592487172a980b59f068a56b9c27164eb305ae401a9672e55"
      url "https://github.com/compozy/compozy/releases/download/v#{version}/compozy_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "4b80db032018813cf38f5acc68bb602480cebddbabd4cb2e790f8d46f3168f04"
      url "https://github.com/compozy/compozy/releases/download/v#{version}/compozy_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e20c8aeb84bb928532bf5cece2e6517116edfd459bbdb48ccedd6f6bf8c7808a"
      url "https://github.com/compozy/compozy/releases/download/v#{version}/compozy_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "3da3223b3f1e038d5934fb2456da815537db75f0e915755b815133981c6eb04d"
      url "https://github.com/compozy/compozy/releases/download/v#{version}/compozy_#{version}_linux_arm64.tar.gz"
    end
  end

  name "compozy"
  desc "Compozy CLI"
  homepage "https://github.com/compozy/compozy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "compozy"

  # No zap stanza required

  caveats <<~EOS
    To get started with Compozy, see https://github.com/compozy/compozy
  EOS
end
