# This file was generated by GoReleaser. DO NOT EDIT.
cask "compozy" do
  version "0.1.7"

  on_macos do
    on_intel do
      url "https://github.com/compozy/compozy/releases/download/v#{version}/compozy_#{version}_darwin_x86_64.tar.gz"
      sha256 "66e9607c4c59db2717532196f1a9b37957e6deb3cb79507651930da146046619"
      rename "compozy_0.1.7_darwin_x86_64/compozy", "compozy"
    end
    on_arm do
      url "https://github.com/compozy/compozy/releases/download/v#{version}/compozy_#{version}_darwin_arm64.tar.gz"
      sha256 "f896320cad71f167672187dfd39f90872b6440624e6371e6fa1075660c71100b"
      rename "compozy_0.1.7_darwin_arm64/compozy", "compozy"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/compozy/compozy/releases/download/v#{version}/compozy_#{version}_linux_x86_64.tar.gz"
      sha256 "48f65c1e483f55206ebdcd7bb497fbb964b570b53a99f15e824c6923a0ea88e7"
      rename "compozy_0.1.7_linux_x86_64/compozy", "compozy"
    end
    on_arm do
      url "https://github.com/compozy/compozy/releases/download/v#{version}/compozy_#{version}_linux_arm64.tar.gz"
      sha256 "79567d81480a8873b1cad5f704a73cdcfddfe2577034723d8bf4a9ec8c0bdd7a"
      rename "compozy_0.1.7_linux_arm64/compozy", "compozy"
    end
  end

  name "compozy"
  desc "Compozy CLI"
  homepage "https://github.com/compozy/compozy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "compozy"

  # No zap stanza required

  caveats <<~EOS
    To get started with Compozy, see https://github.com/compozy/compozy
  EOS
end
