# This file was generated by GoReleaser. DO NOT EDIT.
cask "skeeper" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "fced98b16ffae5f72d843dfe532b989ee4f4c6df59973167f38a8e68fde1385c"
      url "https://github.com/compozy/skeeper/releases/download/v#{version}/skeeper_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "0b989d71f5cf6dc929bcf18d9f86fbe827ba74231b38b98fe268a299ba56d7da"
      url "https://github.com/compozy/skeeper/releases/download/v#{version}/skeeper_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f1e0426e926fc654fccf23a6744cebc9313bf43cd5cc14576adef6cdf5612583"
      url "https://github.com/compozy/skeeper/releases/download/v#{version}/skeeper_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "04ab4382e4a01cb7a9165c055b8cf3b9675d03fbebe056ff67e2b04450c02a54"
      url "https://github.com/compozy/skeeper/releases/download/v#{version}/skeeper_#{version}_linux_arm64.tar.gz"
    end
  end

  name "skeeper"
  desc "Sidecar Git versioning for spec artifacts"
  homepage "https://github.com/compozy/skeeper"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "skeeper"

  # No zap stanza required

  caveats <<~EOS
    To get started with skeeper, see https://github.com/compozy/skeeper
  EOS
end
