# This file was generated by GoReleaser. DO NOT EDIT.
cask "skeeper" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "5f7f2cf4ba83c3ed2f69eb388f04dce42b5e9f49009e307ede9b5200dcdc6621"
      url "https://github.com/compozy/skeeper/releases/download/v#{version}/skeeper_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "0ce0b122891566136533442e176b05decc990bbe4e17bf01b290065276104392"
      url "https://github.com/compozy/skeeper/releases/download/v#{version}/skeeper_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b913b1e145d0cb81f32c3b968e429810942237df0e3f93af2ebd10714409437d"
      url "https://github.com/compozy/skeeper/releases/download/v#{version}/skeeper_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "b10431032496f3091e2227ca2dd3fa660425f6224f1526b6086cb00a2f006396"
      url "https://github.com/compozy/skeeper/releases/download/v#{version}/skeeper_#{version}_linux_arm64.tar.gz"
    end
  end

  name "skeeper"
  desc "Sidecar Git versioning for spec artifacts"
  homepage "https://github.com/compozy/skeeper"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "skeeper"

  # No zap stanza required

  caveats <<~EOS
    To get started with skeeper, see https://github.com/compozy/skeeper
  EOS
end
