# This file was generated by GoReleaser. DO NOT EDIT.
cask "skeeper" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "d56c7ab028576cc50f6e9f3dd4b7c84909ef4baee6dfa9dcb9e98e32d77b0319"
      url "https://github.com/compozy/skeeper/releases/download/v#{version}/skeeper_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "3aa2e55272c6de252f6064cd35fbf4ce328715f6835c3810b6b18be2ba23cd84"
      url "https://github.com/compozy/skeeper/releases/download/v#{version}/skeeper_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "58697a19879045eb0c6f5d92711697f58f78926dc87e772608e8cf99bc614525"
      url "https://github.com/compozy/skeeper/releases/download/v#{version}/skeeper_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "457f1b62137886afa56cdbf48b902b01fc81abc10e4431619ca1a8bbca5b73e1"
      url "https://github.com/compozy/skeeper/releases/download/v#{version}/skeeper_#{version}_linux_arm64.tar.gz"
    end
  end

  name "skeeper"
  desc "Sidecar Git versioning for spec artifacts"
  homepage "https://github.com/compozy/skeeper"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "skeeper"

  # No zap stanza required

  caveats <<~EOS
    To get started with skeeper, see https://github.com/compozy/skeeper
  EOS
end
