# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agh < Formula
  desc "AGH — Artificial General Hivemind"
  homepage "https://agh.network"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/compozy/agh/releases/download/v0.0.3/agh_darwin_x86_64.tar.gz"
      sha256 "8a1bbab0947ddeccfea521cf170573f247acab0bfaf185a5ad10089596479588"

      define_method(:install) do
        bin.install "agh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/compozy/agh/releases/download/v0.0.3/agh_darwin_arm64.tar.gz"
      sha256 "75ecc1eef037a8dc64267c0e971b7c79128f89321c01037180b1209acad50e74"

      define_method(:install) do
        bin.install "agh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/compozy/agh/releases/download/v0.0.3/agh_linux_x86_64.tar.gz"
      sha256 "a123a470a0d92c052c2b546e5f3ff36f69ae6069454d2e6a16548961885a8b37"
      define_method(:install) do
        bin.install "agh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/compozy/agh/releases/download/v0.0.3/agh_linux_arm64.tar.gz"
      sha256 "0ad1f4d5c6c7acdd03af40af1e3c897507bb455454359788957bb282ddd0e8d1"
      define_method(:install) do
        bin.install "agh"
      end
    end
  end

  def caveats
    <<~EOS
      AGH is distributed through the Compozy Homebrew tap. Use `brew upgrade compozy/compozy/agh`
      for managed updates, or set AGH_MANAGED=homebrew in shell wrappers that need
      managed lifecycle diagnostics from `agh update` and `agh uninstall`.
    EOS
  end

  test do
    system "#{bin}/agh", "version"
  end
end
