# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agh < Formula
  desc "AGH — Artificial General Hivemind"
  homepage "https://agh.network"
  version "0.0.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/compozy/agh/releases/download/v0.0.7/agh_darwin_x86_64.tar.gz"
      sha256 "ed5c2a6c04108f8e30ca9cd60b6422ca5c0667e05cee52d25cb995e7f925d597"

      define_method(:install) do
        bin.install "agh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/compozy/agh/releases/download/v0.0.7/agh_darwin_arm64.tar.gz"
      sha256 "5ee6b6573cee247cffd6865494b500a0441ffb803c66eb53b70d766066af8a26"

      define_method(:install) do
        bin.install "agh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/compozy/agh/releases/download/v0.0.7/agh_linux_x86_64.tar.gz"
      sha256 "6700af35a03d022492e12286e7b5d47916427f24f5cb7d5cea69a856553fd706"
      define_method(:install) do
        bin.install "agh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/compozy/agh/releases/download/v0.0.7/agh_linux_arm64.tar.gz"
      sha256 "5b66853e669bb75cfeee91f2201c3e08619417159f2bb0583dca9ac956b3e662"
      define_method(:install) do
        bin.install "agh"
      end
    end
  end

  def caveats
    <<~EOS
      AGH is distributed through the Compozy Homebrew tap. Use `brew upgrade compozy/compozy/agh`
      for managed updates, or set AGH_MANAGED=homebrew in shell wrappers that need
      managed lifecycle diagnostics from `agh update` and `agh uninstall`.
    EOS
  end

  test do
    system "#{bin}/agh", "version"
  end
end
