# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agh < Formula
  desc "AGH — Artificial General Hivemind"
  homepage "https://agh.network"
  version "0.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/compozy/agh/releases/download/v0.0.4/agh_darwin_x86_64.tar.gz"
      sha256 "1a61932e1b93a9e8ba672c6caf8bbf4e9963e30ae644425aa45af79f19cfd40e"

      define_method(:install) do
        bin.install "agh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/compozy/agh/releases/download/v0.0.4/agh_darwin_arm64.tar.gz"
      sha256 "940d50d6bb918eead69230eba19957d25b417e30f751066d224a2f5dfac6b900"

      define_method(:install) do
        bin.install "agh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/compozy/agh/releases/download/v0.0.4/agh_linux_x86_64.tar.gz"
      sha256 "99ac4d3d59519a916439fb632b828c989701029a54817bf862303a19d0ed914e"
      define_method(:install) do
        bin.install "agh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/compozy/agh/releases/download/v0.0.4/agh_linux_arm64.tar.gz"
      sha256 "480ca3944c264aed28bc0ce152b7d383d9ebc85900c659d82eadfa8d50e50429"
      define_method(:install) do
        bin.install "agh"
      end
    end
  end

  def caveats
    <<~EOS
      AGH is distributed through the Compozy Homebrew tap. Use `brew upgrade compozy/compozy/agh`
      for managed updates, or set AGH_MANAGED=homebrew in shell wrappers that need
      managed lifecycle diagnostics from `agh update` and `agh uninstall`.
    EOS
  end

  test do
    system "#{bin}/agh", "version"
  end
end
