# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Compozy < Formula
  desc "Compozy CLI"
  homepage "https://github.com/compozy/compozy"
  version "0.2.15"
  license "BSL-1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/compozy/compozy/releases/download/v0.2.15/compozy_0.2.15_darwin_x86_64.tar.gz"
      sha256 "fe00d83ba785c5236cb17908a6ecfdf98037c2a83076561807a8791e5a7280df"

      define_method(:install) do
        bin.install "compozy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/compozy/compozy/releases/download/v0.2.15/compozy_0.2.15_darwin_arm64.tar.gz"
      sha256 "cf7d2d70c4bc75695230569d10b64770d1a77eb0ed39359867614aa2fbf6842f"

      define_method(:install) do
        bin.install "compozy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/compozy/compozy/releases/download/v0.2.15/compozy_0.2.15_linux_x86_64.tar.gz"
      sha256 "339f5552c7dd19c737b26eedc2b288e94fb1159480f02bff1ecca2e709c9ec13"
      define_method(:install) do
        bin.install "compozy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/compozy/compozy/releases/download/v0.2.15/compozy_0.2.15_linux_arm64.tar.gz"
      sha256 "d863182b2d6c311335139c881646203281ca2f7235668a2cba15d519e18d4ac3"
      define_method(:install) do
        bin.install "compozy"
      end
    end
  end

  def caveats
    <<~EOS
      To get started with Compozy, see https://github.com/compozy/compozy
    EOS
  end

  test do
    system "#{bin}/compozy", "--version"
  end
end
