# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Compozy < Formula
  desc "Compozy CLI"
  homepage "https://github.com/compozy/compozy"
  version "0.2.5"
  license "BSL-1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/compozy/compozy/releases/download/v0.2.5/compozy_0.2.5_darwin_x86_64.tar.gz"
      sha256 "d9632934bd955f9ec5dfd8cba3e76356d310965a16db1b2ee0a66281392a3340"

      define_method(:install) do
        bin.install "compozy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/compozy/compozy/releases/download/v0.2.5/compozy_0.2.5_darwin_arm64.tar.gz"
      sha256 "78f6209b07c2fbe73da4646c8e398acb7a90cce288c2a9cf9971e466625b84df"

      define_method(:install) do
        bin.install "compozy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/compozy/compozy/releases/download/v0.2.5/compozy_0.2.5_linux_x86_64.tar.gz"
      sha256 "1eca79337d83508de727cc12a607790c342502f4b7c6a057ee41be20960cdcd0"
      define_method(:install) do
        bin.install "compozy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/compozy/compozy/releases/download/v0.2.5/compozy_0.2.5_linux_arm64.tar.gz"
      sha256 "170728ee4fba795a8d9385d556560f7d6cb74586e672eac8d1b1d4babc051b53"
      define_method(:install) do
        bin.install "compozy"
      end
    end
  end

  def caveats
    <<~EOS
      To get started with Compozy, see https://github.com/compozy/compozy
    EOS
  end

  test do
    system "#{bin}/compozy", "--version"
  end
end
