# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skeeper < Formula
  desc "Sidecar Git versioning for spec artifacts"
  homepage "https://github.com/compozy/skeeper"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/compozy/skeeper/releases/download/v0.3.1/skeeper_0.3.1_darwin_x86_64.tar.gz"
      sha256 "00070855c82419397178a6aa02c6bb2cf7c68e071beaa33d63a85d5382825c91"

      define_method(:install) do
        bin.install "skeeper"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/compozy/skeeper/releases/download/v0.3.1/skeeper_0.3.1_darwin_arm64.tar.gz"
      sha256 "15f46e742b052f0cf951005da1423f18839a2456d44ea1fb4c1af29d87f7ad51"

      define_method(:install) do
        bin.install "skeeper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/compozy/skeeper/releases/download/v0.3.1/skeeper_0.3.1_linux_x86_64.tar.gz"
      sha256 "c3e0be2aed48dab01ec9bf87130a81c7ffd06d74d1e30f88af56b535a955e2b7"
      define_method(:install) do
        bin.install "skeeper"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/compozy/skeeper/releases/download/v0.3.1/skeeper_0.3.1_linux_arm64.tar.gz"
      sha256 "c7efb45f1d3228f7a6c350fbe8635e7ff715234b917e0112676a7dc6c5b212ab"
      define_method(:install) do
        bin.install "skeeper"
      end
    end
  end

  def caveats
    <<~EOS
      To get started with skeeper, see https://github.com/compozy/skeeper
    EOS
  end

  test do
    system "#{bin}/skeeper", "version"
  end
end
